Iter13
ScreamSoul/go-metrics-tpl pull request #13
Opened 2024-04-15 20:57 UTC by ScreamSoul

2024-04-17 09:31 UTC, arttet requested changes

2024-04-17 09:31 UTC, arttet commented on .env
CHANGE REQUEST: it shouldn't be in Git.

2024-04-17 09:31 UTC, arttet commented on .gitignore
> +*.json
```suggestion
*.json
.env
```

2024-04-17 09:31 UTC, arttet commented on internal/models/metrics/metrics.go
> +	aux := &struct {
CHANGE REQUEST: could you please definition this struct in the mode package

2024-04-17 09:31 UTC, arttet commented on internal/repositories/postgres/bootstrap.go
> +	createTableQuery := `
CHANGE REQUEST: please use migrations

2024-04-17 09:31 UTC, arttet commented on internal/repositories/postgres/bootstrap.go
> +		m_type VARCHAR(255) NOT NULL CHECK (m_type IN ('gauge', 'counter')),
CHANGE REQUEST: please use `enum`

2024-04-17 15:35 UTC, ScreamSoul commented on internal/models/metrics/metrics.go
> +	aux := &struct {
Не совсем понял в чем задумка

если выносить эту структуру в другой пакет (mode) то получится цикличный импорт

2024-04-21 14:16 UTC, arttet approved these changes

2024-05-13 13:25 UTC, merged