Iter5
ScreamSoul/go-metrics-tpl pull request #5
Opened 2024-03-11 13:45 UTC by ScreamSoul

2024-03-11 16:11 UTC, arttet requested changes
Good job!

Please add
- https://about.codecov.io/blog/getting-started-with-code-coverage-for-golang/
- https://github.com/golangci/golangci-lint

2024-03-11 16:11 UTC, arttet commented on cmd/agent/configs.go
> +var cfg Config
CHANGE REQUEST: please don't use global variables

2024-03-11 16:11 UTC, arttet commented on cmd/agent/main.go
> +type Metrics struct {
CHANGE REQUEST: please move it to another package

2024-03-11 16:11 UTC, arttet commented on internal/handlers/metrics.go
> +	metricObj.Type = metric.MetricType(r.PathValue("metric_type"))
SUGGESTION: it would be better if you add a construction function.

2024-03-13 16:02 UTC, ScreamSoul commented
<img width="732" alt="image" src="https://github.com/ScreamSoul/go-metrics-tpl/assets/126969214/78123ba2-cfad-4136-be5b-5ac5f918dec7">


Так все уже добавлено 
<img width="282" alt="image" src="https://github.com/ScreamSoul/go-metrics-tpl/assets/126969214/0a40abb2-2e9d-4891-b97d-cff96412d052">
<img width="832" alt="image" src="https://github.com/ScreamSoul/go-metrics-tpl/assets/126969214/8f624d5e-3727-4530-9197-ba53b46c1e8a">

2024-03-13 16:42 UTC, arttet commented
> <img alt="image" width="732" src="https://private-user-images.githubusercontent.com/126969214/312533949-78123ba2-cfad-4136-be5b-5ac5f918dec7.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTAzNDg0MzQsIm5iZiI6MTcxMDM0ODEzNCwicGF0aCI6Ii8xMjY5NjkyMTQvMzEyNTMzOTQ5LTc4MTIzYmEyLWNmYWQtNDEzNi1iZTViLTVhYzVmOTE4ZGVjNy5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMzEzJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDMxM1QxNjQyMTRaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT02Yjc4ZmQyNGRiYWIwMDBhZDQ0NDlmYmM1YmY2NDYxYTI1NDkzNmQwNGNiZGFiZjBmMDBlNmViMWM2OWRhYmE5JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.rEuF3LN3Jb3gbBTor3kkq8oUAfGlUs4oelaMgbBMmcI">
> Так все уже добавлено <img alt="image" width="282" src="https://private-user-images.githubusercontent.com/126969214/312533774-0a40abb2-2e9d-4891-b97d-cff96412d052.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTAzNDg0MzQsIm5iZiI6MTcxMDM0ODEzNCwicGF0aCI6Ii8xMjY5NjkyMTQvMzEyNTMzNzc0LTBhNDBhYmIyLTJlOWQtNDg5MS1iOTdkLWNmZjk2NDEyZDA1Mi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMzEzJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDMxM1QxNjQyMTRaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0wYTg3ZTRlZjQ4N2ZlYzNiMjRhMTQ0MDNmZTVhNTdkOWI0ZGVhNjgyZWVkMzU1ODkwNmE2NWVhZDlmYjEyZDg0JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.47a3KpEXsifW5YYOswD1-t_ea4VfB3O7u03TcYIsd3A"> <img alt="image" width="832" src="https://private-user-images.githubusercontent.com/126969214/312534048-8f624d5e-3727-4530-9197-ba53b46c1e8a.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTAzNDg0MzQsIm5iZiI6MTcxMDM0ODEzNCwicGF0aCI6Ii8xMjY5NjkyMTQvMzEyNTM0MDQ4LThmNjI0ZDVlLTM3MjctNDUzMC05MTk3LWJhNTNiNDZjMWU4YS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMzEzJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDMxM1QxNjQyMTRaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0wNGZkNTc3YzI5MzdhNTNkY2FlZmE1MTE4NTVjZmU5NzQ1MDEwNjgyYTg2MWI5MjRhOWMzODQwODVkNzY4Yzc3JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.1lkcgHjGkAoekAwqvJHvPhJyCyW5PGFSIAD_12dHf4M">

https://github.com/ScreamSoul/go-metrics-tpl/pull/5#issuecomment-1994794084

2024-03-13 16:52 UTC, arttet requested changes

2024-03-13 16:52 UTC, arttet commented on .github/workflows/coverage.yml
> +        uses: codecov/codecov-action@v3
```suggestion
        uses: codecov/codecov-action@v4
```

2024-03-13 16:52 UTC, arttet commented on .github/workflows/coverage.yml
> +      - uses: actions/checkout@v2
```suggestion
      - uses: actions/checkout@v4
```

2024-03-13 16:52 UTC, arttet commented on cmd/agent/configs.go
> +var cfg config
CHANGE REQUEST: please don't use global variables

2024-03-13 19:24 UTC, ScreamSoul commented on .github/workflows/coverage.yml
> +        uses: codecov/codecov-action@v3
Сделал по инструкции https://docs.codecov.com/docs/quick-start
Но репозиторий так и не появился, поэтому решил отказаться от этого шага
<img width="1064" alt="image" src="https://github.com/ScreamSoul/go-metrics-tpl/assets/126969214/d2156910-1b54-42ab-be07-f50b4215273b">

2024-03-15 16:28 UTC, arttet approved these changes

2024-03-15 16:28 UTC, arttet commented on cmd/agent/main.go
> +	fmt.Printf("Url: %s; Status: %s\r\n", uploadURL, resp.Status)
```suggestion
	defer resp.Body.Close()
	fmt.Printf("Url: %s; Status: %s\r\n", uploadURL, resp.Status)
```

2024-03-15 16:28 UTC, arttet commented on .github/workflows/coverage.yml
> +        uses: actions/upload-artifact@v1
SUGGESTION: you need to use another action.

2024-03-15 16:28 UTC, arttet commented on internal/handlers/metrics.go
> +	(*ms.store).Add(metricObj)
```suggestion
	ms.store.Add(metricObj)
```

2024-03-15 16:28 UTC, arttet commented on internal/handlers/metrics.go
> +	var mt = metric.MetricType(r.PathValue("metric_type"))
```suggestion
	mt := metric.MetricType(r.PathValue("metric_type"))
```

2024-03-18 10:02 UTC, merged